---
apiVersion: v1
kind: service
metadata:
  name: voting-app-service
  labels:
    author: yugo
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: voting-app-deployment
...
